# Generated by Django 4.0.1 on 2022-01-30 12:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receitas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='receitas',
            new_name='Receita',
        ),
    ]
